SHORTENED_APPLICATION = """\
ID ID_NUM | POSITION_NAME (COMPANY_NAME) - PRIORITY_NUM★
CURRENT_STATUS | Applied: APPLICATION_DATE INTERVIEW_DATE
Contact: CONTACT_ADDRESS\
"""

FULL_APPLICATION = """\
ID ID_NUM | POSITION_NAME (COMPANY_NAME) - PRIORITY_NUM★
CURRENT_STATUS | Applied: APPLICATION_DATE INTERVIEW_DATE
Contact: CONTACT_ADDRESS URL_ADDRESS LOCATION_ADDRESS
FULL_DESCRIPTION
FULL_NOTES\
"""