SHORTENED_APPLICATION = """\
ID ID_NUM / POSITION_NAME (COMPANY_NAME) - PRIORITY_NUM★
CURRENT_STATUS / Applied: APPLICATION_DATE / Interview: INTERVIEW_DATE
Contact: CONTACT_ADDRESS\
"""

FULL_APPLICATION = """\
ID ID_NUM / POSITION_NAME (COMPANY_NAME) - PRIORITY_NUM★
CURRENT_STATUS / Applied: APPLICATION_DATE / Interview: INTERVIEW_DATE
Contact: CONTACT_ADDRESS / Url: URL_ADDRESS / Location: LOCATION_ADDRESS
Description:
FULL_DESCRIPTION
Notes:
FULL_NOTES\
"""